- hosts: "all" # применяем команды ко всем хостам в inventory
  become: true # становимся привилегированным пользователем
  
  tasks: # список тасков
  # NGINX
  - name: "Install nginx via yum" # имя, обязательно для любой таски из плейбука, должно содержать описание того что эта таска делает 
    ansible.builtin.yum: # имя модуля, этот модуль устанавливает софт на хосте с помощью пакета apt
      name: "nginx" # имя пакета для установки
      state: "latest" # установить последнюю версию пакета, в отличие от present, если пакет уже установлен в системе, попробует его обновить
      update_cache: true # вызвать apt update перед установкой, чтобы убедиться в наличии самой свежей базы данных о пакетах
    
  - name: "Delete /var/www/html folder"
    ansible.builtin.file: # этот модуль работает с файлами и папками на удаленной машине
      path: "/var/www/html" # путь к файлу/папке на удаленной машине
      state: "absent" # перевести папку в состояние absent - то есть удалить ее
  
  - name: "Copy our landing to /var/www/html folder"
    ansible.builtin.copy: # этот модуль копирует файлы/директории с контрольной ноды на хосты
      src: "files/html" # путь к файлу/директории для копирования на контрольной ноде
      dest: "/var/www/" # путь для вставки на удаленной машине, вставка папок ВСЕГДА будет осуществляться внутрь папки, ансибл никогда не будет подменять папки или   переименовывать их
      #owner: "vagrant" # пользователь владелец файла/директории на удаленной машине
      #group: "vagrant " # группа владелец файла/директории на удаленной машине
      #mode: "0644" # права доступа к файлу/ директории

  - name: "Edit Firewall"
    shell: "sed -i 's#/usr/share/nginx/html#/var/www/html/#' /etc/nginx/nginx.conf"

  - name: "Start nginx"
    shell: "systemctl start nginx | systemctl enable nginx"

  - name: "Edit Firewall"
    shell: "firewall-cmd --zone=public --add-port=80/tcp --permanent | systemctl stop firewalld.service | systemctl start firewalld.service"


  # PHP
  - name: "Installing php fpm and php mysql"
    ansible.builtin.yum:
      name: "{{ item }}" # здесь мы будем перечислять пакеты для установки, поэтому вместо имени здесь плейсхолдер
      state: "latest"
      update_cache: true
    with_items: # а вот тут уже и перечисляем, ansible сам их подcтавит вместо {{ name }}
      - "php-fpm"
      - "php-mysql"

  - name: "Copy php files to /var/www"
    ansible.builtin.copy:
      src: "files/test-php/php_test"
      dest: "/var/www/"
      #owner: "vagrant"
      #group: "vagrant"
      #mode: "0644"

  # - name: "Copy nginx config for php testing"
  #   ansible.builtin.copy:
  #     src: "files/test-php/nginx.conf"
  #     dest: "/etc/nginx/sites-available/php_test.conf"
  #     #owner: "vagrant"
  #     #group: "vagrant"
  #     #mode: "0644"

  # - name: "Link folder"
  #   ansible.builtin.file:
  #     src: "/etc/nginx/sites-available/php_test.conf"
  #     dest: "/etc/nginx/sites-enabled/php_test"
  #     state: "link" # здесь создаем симлинк

  # - name: "Reload nginx"
  #   ansible.builtin.service:
  #     name: "nginx"
  #     state: "reloaded"    
